---

name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm
      - name: Install dependencies
        run: npm clean-install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
